// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Eip7702Support$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Eip7702Support";
  readonly sourceName: "contracts/core/Eip7702Support.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"sender","type":"address"}],"name":"Eip7702SenderNotDelegate","type":"error"},{"inputs":[{"internalType":"address","name":"sender","type":"address"}],"name":"Eip7702SenderWithoutCode","type":"error"}];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220cf81476dbc407b762631827cc7e1e1c1f87f2070320e8b938a21d5d44caa553f64736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220cf81476dbc407b762631827cc7e1e1c1f87f2070320e8b938a21d5d44caa553f64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/core/Eip7702Support.sol";
  readonly buildInfoId: "solc-0_8_28-7ff7631a7cdd57a86742051c063fe36f91905a53";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Eip7702Support"]: Eip7702Support$Type;
    ["contracts/core/Eip7702Support.sol:Eip7702Support"]: Eip7702Support$Type;
  }
}