/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { Eip7702Support, Eip7702SupportInterface } from "../../core/Eip7702Support.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "Eip7702SenderNotDelegate",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      }
    ],
    "name": "Eip7702SenderWithoutCode",
    "type": "error"
  }
] as const;

  const _bytecode = "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220cf81476dbc407b762631827cc7e1e1c1f87f2070320e8b938a21d5d44caa553f64736f6c634300081c0033";

  
      type Eip7702SupportConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: Eip7702SupportConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Eip7702Support__factory extends ContractFactory {
    
      constructor(...args: Eip7702SupportConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Eip7702Support & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Eip7702Support__factory {
      return super.connect(runner) as Eip7702Support__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): Eip7702SupportInterface {
      return new Interface(_abi) as Eip7702SupportInterface;
    }
    
    override attach(address: string | Addressable): Eip7702Support {
      return super.attach(address) as Eip7702Support;
    }
  static connect(address: string, runner?: ContractRunner | null): Eip7702Support {
      return new Contract(address, _abi, runner) as unknown as Eip7702Support;
    }
  }

  
  