/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { UserOperationLib, UserOperationLibInterface } from "../../core/UserOperationLib.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "dataLength",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "pmSignatureLength",
        "type": "uint256"
      }
    ],
    "name": "InvalidPaymasterSignatureLength",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "PAYMASTER_DATA_OFFSET",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "PAYMASTER_POSTOP_GAS_OFFSET",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "PAYMASTER_VALIDATION_GAS_OFFSET",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x61010a61004d600b8282823980515f1a6073146041577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106046575f3560e01c806325093e1b14604a578063b29a8ff4146064578063ede3150214607e575b5f5ffd5b60506098565b604051605b919060bd565b60405180910390f35b606a609d565b6040516075919060bd565b60405180910390f35b608460a2565b604051608f919060bd565b60405180910390f35b602481565b601481565b603481565b5f819050919050565b60b78160a7565b82525050565b5f60208201905060ce5f83018460b0565b9291505056fea2646970667358221220d3dedaa31ef412e3009593cf6db90f1b0b9c9e739d0b75a6b3a6b7e364fae3d964736f6c634300081c0033";

  
      type UserOperationLibConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: UserOperationLibConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class UserOperationLib__factory extends ContractFactory {
    
      constructor(...args: UserOperationLibConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<UserOperationLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): UserOperationLib__factory {
      return super.connect(runner) as UserOperationLib__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): UserOperationLibInterface {
      return new Interface(_abi) as UserOperationLibInterface;
    }
    
    override attach(address: string | Addressable): UserOperationLib {
      return super.attach(address) as UserOperationLib;
    }
  static connect(address: string, runner?: ContractRunner | null): UserOperationLib {
      return new Contract(address, _abi, runner) as unknown as UserOperationLib;
    }
  }

  
  