/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'TokenCallbackHandler', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenCallbackHandler__factory>
getContractFactory(name: 'Simple7702Account', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Simple7702Account__factory>
getContractFactory(name: 'SimpleAccount', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimpleAccount__factory>
getContractFactory(name: 'SimpleAccountFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimpleAccountFactory__factory>
getContractFactory(name: 'BaseAccount', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BaseAccount__factory>
getContractFactory(name: 'BasePaymaster', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BasePaymaster__factory>
getContractFactory(name: 'Eip7702Support', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Eip7702Support__factory>
getContractFactory(name: 'EntryPoint', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EntryPoint__factory>
getContractFactory(name: 'EntryPointSimulations', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EntryPointSimulations__factory>
getContractFactory(name: 'NonceManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NonceManager__factory>
getContractFactory(name: 'SenderCreator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SenderCreator__factory>
getContractFactory(name: 'Stakeable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Stakeable__factory>
getContractFactory(name: 'StakeManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.StakeManager__factory>
getContractFactory(name: 'UserOperationLib', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UserOperationLib__factory>
getContractFactory(name: 'IAccount', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAccount__factory>
getContractFactory(name: 'IAccountExecute', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAccountExecute__factory>
getContractFactory(name: 'IAggregator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAggregator__factory>
getContractFactory(name: 'IEntryPoint', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEntryPoint__factory>
getContractFactory(name: 'IEntryPointSimulations', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEntryPointSimulations__factory>
getContractFactory(name: 'INonceManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INonceManager__factory>
getContractFactory(name: 'IPaymaster', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPaymaster__factory>
getContractFactory(name: 'ISenderCreator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ISenderCreator__factory>
getContractFactory(name: 'IStakeManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStakeManager__factory>
getContractFactory(name: 'IAccount06', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAccount06__factory>
getContractFactory(name: 'IAggregator06', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAggregator06__factory>
getContractFactory(name: 'IEntryPoint', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEntryPoint__factory>
getContractFactory(name: 'INonceManager06', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.INonceManager06__factory>
getContractFactory(name: 'IPaymaster06', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPaymaster06__factory>
getContractFactory(name: 'IStakeManager06', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IStakeManager06__factory>

  getContractAt(name: 'TokenCallbackHandler', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenCallbackHandler>
getContractAt(name: 'Simple7702Account', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Simple7702Account>
getContractAt(name: 'SimpleAccount', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimpleAccount>
getContractAt(name: 'SimpleAccountFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimpleAccountFactory>
getContractAt(name: 'BaseAccount', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BaseAccount>
getContractAt(name: 'BasePaymaster', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BasePaymaster>
getContractAt(name: 'Eip7702Support', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Eip7702Support>
getContractAt(name: 'EntryPoint', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EntryPoint>
getContractAt(name: 'EntryPointSimulations', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EntryPointSimulations>
getContractAt(name: 'NonceManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NonceManager>
getContractAt(name: 'SenderCreator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SenderCreator>
getContractAt(name: 'Stakeable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Stakeable>
getContractAt(name: 'StakeManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.StakeManager>
getContractAt(name: 'UserOperationLib', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UserOperationLib>
getContractAt(name: 'IAccount', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAccount>
getContractAt(name: 'IAccountExecute', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAccountExecute>
getContractAt(name: 'IAggregator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAggregator>
getContractAt(name: 'IEntryPoint', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEntryPoint>
getContractAt(name: 'IEntryPointSimulations', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEntryPointSimulations>
getContractAt(name: 'INonceManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INonceManager>
getContractAt(name: 'IPaymaster', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPaymaster>
getContractAt(name: 'ISenderCreator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ISenderCreator>
getContractAt(name: 'IStakeManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStakeManager>
getContractAt(name: 'IAccount06', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAccount06>
getContractAt(name: 'IAggregator06', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAggregator06>
getContractAt(name: 'IEntryPoint', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEntryPoint>
getContractAt(name: 'INonceManager06', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.INonceManager06>
getContractAt(name: 'IPaymaster06', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPaymaster06>
getContractAt(name: 'IStakeManager06', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IStakeManager06>

  deployContract(name: 'TokenCallbackHandler', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenCallbackHandler>
deployContract(name: 'Simple7702Account', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Simple7702Account>
deployContract(name: 'SimpleAccount', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleAccount>
deployContract(name: 'SimpleAccountFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleAccountFactory>
deployContract(name: 'BaseAccount', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseAccount>
deployContract(name: 'BasePaymaster', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BasePaymaster>
deployContract(name: 'Eip7702Support', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Eip7702Support>
deployContract(name: 'EntryPoint', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EntryPoint>
deployContract(name: 'EntryPointSimulations', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EntryPointSimulations>
deployContract(name: 'NonceManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NonceManager>
deployContract(name: 'SenderCreator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SenderCreator>
deployContract(name: 'Stakeable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Stakeable>
deployContract(name: 'StakeManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakeManager>
deployContract(name: 'UserOperationLib', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UserOperationLib>
deployContract(name: 'IAccount', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccount>
deployContract(name: 'IAccountExecute', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccountExecute>
deployContract(name: 'IAggregator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAggregator>
deployContract(name: 'IEntryPoint', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEntryPoint>
deployContract(name: 'IEntryPointSimulations', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEntryPointSimulations>
deployContract(name: 'INonceManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INonceManager>
deployContract(name: 'IPaymaster', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPaymaster>
deployContract(name: 'ISenderCreator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISenderCreator>
deployContract(name: 'IStakeManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakeManager>
deployContract(name: 'IAccount06', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccount06>
deployContract(name: 'IAggregator06', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAggregator06>
deployContract(name: 'IEntryPoint', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEntryPoint>
deployContract(name: 'INonceManager06', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INonceManager06>
deployContract(name: 'IPaymaster06', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPaymaster06>
deployContract(name: 'IStakeManager06', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakeManager06>

  deployContract(name: 'TokenCallbackHandler', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenCallbackHandler>
deployContract(name: 'Simple7702Account', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Simple7702Account>
deployContract(name: 'SimpleAccount', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleAccount>
deployContract(name: 'SimpleAccountFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleAccountFactory>
deployContract(name: 'BaseAccount', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BaseAccount>
deployContract(name: 'BasePaymaster', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BasePaymaster>
deployContract(name: 'Eip7702Support', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Eip7702Support>
deployContract(name: 'EntryPoint', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EntryPoint>
deployContract(name: 'EntryPointSimulations', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EntryPointSimulations>
deployContract(name: 'NonceManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NonceManager>
deployContract(name: 'SenderCreator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SenderCreator>
deployContract(name: 'Stakeable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Stakeable>
deployContract(name: 'StakeManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.StakeManager>
deployContract(name: 'UserOperationLib', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UserOperationLib>
deployContract(name: 'IAccount', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccount>
deployContract(name: 'IAccountExecute', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccountExecute>
deployContract(name: 'IAggregator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAggregator>
deployContract(name: 'IEntryPoint', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEntryPoint>
deployContract(name: 'IEntryPointSimulations', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEntryPointSimulations>
deployContract(name: 'INonceManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INonceManager>
deployContract(name: 'IPaymaster', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPaymaster>
deployContract(name: 'ISenderCreator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ISenderCreator>
deployContract(name: 'IStakeManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakeManager>
deployContract(name: 'IAccount06', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAccount06>
deployContract(name: 'IAggregator06', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAggregator06>
deployContract(name: 'IEntryPoint', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEntryPoint>
deployContract(name: 'INonceManager06', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.INonceManager06>
deployContract(name: 'IPaymaster06', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPaymaster06>
deployContract(name: 'IStakeManager06', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IStakeManager06>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  