// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Exec$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Exec";
  readonly sourceName: "contracts/utils/Exec.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212200baf46b08c1e3f1a1d641e587c61aaf455d992d7919b8bc11e2c32b83b9be0e864736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212200baf46b08c1e3f1a1d641e587c61aaf455d992d7919b8bc11e2c32b83b9be0e864736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/utils/Exec.sol";
  readonly buildInfoId: "solc-0_8_28-7ff7631a7cdd57a86742051c063fe36f91905a53";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Exec"]: Exec$Type;
    ["contracts/utils/Exec.sol:Exec"]: Exec$Type;
  }
}