// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ISenderCreator$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ISenderCreator";
  readonly sourceName: "contracts/interfaces/ISenderCreator.sol";
  readonly abi: [{"inputs":[{"internalType":"bytes","name":"initCode","type":"bytes"}],"name":"createSender","outputs":[{"internalType":"address","name":"sender","type":"address"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"sender","type":"address"},{"internalType":"bytes","name":"initCallData","type":"bytes"}],"name":"initEip7702Sender","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ISenderCreator.sol";
  readonly buildInfoId: "solc-0_8_28-3f4ee4630f9d01cfee2851f8451d28cd4ac21008";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ISenderCreator"]: ISenderCreator$Type;
    ["contracts/interfaces/ISenderCreator.sol:ISenderCreator"]: ISenderCreator$Type;
  }
}